/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codingdie_speex_SpeexUtils */

#ifndef _Included_com_codingdie_speex_SpeexUtils
#define _Included_com_codingdie_speex_SpeexUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codingdie_speex_SpeexUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_codingdie_speex_SpeexUtils_decode
  (JNIEnv * p1, jobject p2, jstring p3, jstring p4);

#ifdef __cplusplus
}
#endif
#endif
